name: violin
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  cached_network_image: ^3.2.2
  dio: ^4.0.6
  get_it: ^7.2.0
  url_launcher: ^6.1.6
  sqflite: ^2.3.0
  shared_preferences: ^2.2.0
  bdd_widget_test: ^1.2.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
